name: Build and Release

on:
  push:
    branches:
      - new-br

jobs:
  build:
    name: Build and Upload to Pre-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build with Arch Linux
        run: |
          docker run --name arch_build -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman-key --init && \
          pacman-key --populate archlinux && \
          pacman -Syu --noconfirm && \
          pacman -S --noconfirm base-devel pipewire &&\
          make"

      - name: Get short commit SHA and commit count
        id: vars
        run: | 
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Create Pre-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "build-${{ env.SHORT_SHA }}-${{ env.COMMIT_NUMBER }}"
          release_name: "Build from commit ${{ env.SHORT_SHA }}"
          prerelease: true
          draft: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./awim
          asset_name: awim
          asset_content_type: application/octet-stream

